#pragma config(Sensor, in1,    PT_1,           sensorPotentiometer)
#pragma config(Motor,  port1,           BL_BASE,       tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FL_BASE,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           TL_LIFT,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           CLAW,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           TR_LIFT,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FR_BASE,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          BR_BASE,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//THIS IS FOR THE NEW ROBOT

/*CHANGE LOG:
9/20/2018: Changed the condition in the while loop from 1==1 to true- it's a matter of personal preference, but either works.
Changed the control structure from if/else if/else form to a if/else if/else form. Changed commands in lift to mirror the control
of the base. Are the units in the wait command seconds? Debating the removal of the stopMotor/motor = 0 and commands from within
the up and down functions for the lift. Removed the == 1 from the button control, its uneccesary. No auton yet.
Adding code for the claw.

9/28/2018: Changed the code to match the driver code in the competition file if we need to test just this code.
*/


//NOTE: this is for DRIVER CONTROL
task main()
{
	int tank = 1;
	int arcade = 0;
  	while (true){

		if(vexRT[Btn7R]==1)
			{
			tank=1;
			arcade=0;
			}
if(vexRT[Btn7L]==1)
		{
		tank=0;
		arcade=1;
		}
// This is Tank Control
if(tank)
		{
		motor[BL_BASE] = vexRT[Ch3];
		motor[FL_BASE] = vexRT[Ch3];
		motor[BR_BASE] = vexRT[Ch2];
		motor[FR_BASE] = vexRT[Ch2];
		}

//This is Arcade Control
if(arcade)
		{
		motor[BL_BASE] = (vexRT[Ch3]+vexRT[Ch4])/2;
		motor[FL_BASE] = (vexRT[Ch3]+vexRT[Ch4])/2;
		motor[BR_BASE] = (vexRT[Ch3]-vexRT[Ch4])/2;
		motor[FR_BASE] = (vexRT[Ch3]-vexRT[Ch4])/2;
		}


		//start of LIFT CONTROL
		if(vexRT[Btn8U])//moves lift up
		{
			motor[TL_LIFT] = 63.5;
			motor[TR_LIFT] = 63.5;
		}
		else if(vexRT[Btn8D])//moves lift down
		{
			motor[TL_LIFT] = -63.5;
			motor[TR_LIFT] = -63.5;
		}
		else//sets speed of lift motors to zero
		{
			motor[TL_LIFT] = 0;
			motor[TR_LIFT] = 0;
		}
		//end of LIFT control


		//start of CLAW control
			if(vexRT[Btn6U]==1)
	  {
				motor[CLAW] = 37.5;
		}

		else if(vexRT[Btn6D]){
			motor[CLAW] = -37.5;
		}

		else
		{
			motor[CLAW] = 0;
		}
		//end of CLAW control
	}
}
