#pragma config(Sensor, in1,    PT_1,           sensorPotentiometer)
#pragma config(Motor,  port1,           BL_BASE,       tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FL_BASE,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           TL_LIFT,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           CLAW,          tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           TR_LIFT,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           FR_BASE,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          BR_BASE,       tmotorVex393HighSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1==1)
	{
		motor[BL_BASE] = vexRT[Ch3];
		motor[FL_BASE] = vexRT[Ch3];
		motor[BR_BASE] = vexRT[Ch2];
		motor[FR_BASE] = vexRT[Ch2];




		if(vexRT[Btn8U] == 1)
		{
			startMotor(TL_LIFT, 127);
			startMotor(TR_LIFT, 127);
			wait(1.375);
			stopMotor(TL_LIFT);
		  stopMotor(TR_LIFT);
		}

		else
		{
			stopMotor(TL_LIFT);
			stopMotor(TR_LIFT);
		}

		if(vexRT[Btn8D] == 1)
		{
			startMotor(TL_LIFT, -100);
			startMotor(TR_LIFT, -100);
			wait(1.375);
			stopMotor(TL_LIFT);
		  stopMotor(TR_LIFT);
		}

		else
		{
			stopMotor(TL_LIFT);
			stopMotor(TR_LIFT);
		}
	}
}
